# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch


# Create random tensor
tensor_A=torch.rand(7,7)
tensor_A.shape, tensor_A


(torch.Size([7, 7]),
 tensor([[0.0966, 0.4198, 0.6539, 0.9077, 0.6071, 0.5122, 0.8664],
         [0.0277, 0.2941, 0.2014, 0.3863, 0.5289, 0.3862, 0.3325],
         [0.4286, 0.4485, 0.7542, 0.5880, 0.3706, 0.8853, 0.6078],
         [0.9213, 0.9043, 0.3705, 0.4248, 0.0793, 0.3042, 0.1178],
         [0.8947, 0.4754, 0.1802, 0.2378, 0.7989, 0.4645, 0.9915],
         [0.9977, 0.7594, 0.3083, 0.0483, 0.0153, 0.4806, 0.6796],
         [0.0983, 0.1806, 0.5528, 0.8415, 0.2932, 0.3682, 0.7948]]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor

# Perform matrix multiplication
tensor_B=torch.rand(1,7)
# print(tensor_B.T)
tensor_C=tensor_A@tensor_B.T
# tensor_B, tensor_C
print(tensor_C.shape)
print(tensor_C)




torch.Size([7, 1])
tensor([[2.7665],
        [1.4616],
        [2.4020],
        [1.9198],
        [2.7523],
        [2.0551],
        [2.0878]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
RANDOM_SEED=0
torch.manual_seed(seed=RANDOM_SEED)

# Create two random tensors

tensor_D=torch.rand(7,7)
tensor_D
tensor_E=torch.rand(1,7)
tensor_E
# Matrix multiply tensors
tensor_F=tensor_D.matmul(tensor_E.T)
tensor_F

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [7]:
# Set random seed on the GPU
torch.cuda.is_available()
torch.cuda.device_count()

torch.cuda.manual_seed(1234)

'cuda'


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [10]:
# Set random seed
torch.manual_seed(1234)
print(device)
# Check for access to GPU
device="cuda" if torch.cuda.is_available else "cpu"
device
# Create two random tensors on GPU
tensor_ga=torch.rand(2,3).to(device)
tensor_gb=torch.rand(2,3).to(device)
tensor_ga, tensor_gb

cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [11]:
# Perform matmul on tensor_A and tensor_B
tensor_gc=tensor_ga.matmul(tensor_gb.T)
tensor_gc, tensor_gc.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max

# Find min


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
