<a href="https://colab.research.google.com/github/raiyan666/Pytorch_zero_to_mastery/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git --version


git version 2.34.1


In [2]:
!git config --global user.email "raiyan.yead124@gmail.com"
!git config --global user.name "raiyan666"

In [3]:
!git clone https://github.com/raiyan666/Pytotch_zero_to_mastery.git
%cd Pytotch_zero_to_mastery

Cloning into 'Pytotch_zero_to_mastery'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (6/6), done.
/content/Pytotch_zero_to_mastery


In [4]:
!git add .

In [5]:
!git commit -m "Add my new files from Colab"

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean


In [6]:
# !nvidia-smi

In [7]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


###Introduction To Tensor
###Creating Tensor  

In [8]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim

0

In [10]:
#get tensor back as python int
scalar.item()

7

In [11]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [12]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

In [14]:
matrix=torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
matrix.ndim

2

In [16]:
matrix[1]

tensor([ 9, 10])

In [17]:
matrix[0]

tensor([7, 8])

In [18]:
matrix.shape

torch.Size([2, 2])

In [19]:
#Tensor
tensor=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,3,5]]])
tensor


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 3, 5]]])

In [20]:
tensor.ndim

3

In [21]:
tensor.shape

torch.Size([1, 3, 3])

In [22]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 3, 5]])

###Random Tensors

In [23]:
#Create a random tensor of size(3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.8789, 0.8513, 0.3650, 0.3226],
        [0.2744, 0.7024, 0.1738, 0.3811],
        [0.9775, 0.5055, 0.6149, 0.7436]])

In [24]:
random_tensor.ndim

2

In [25]:
random_image_size_tensor=torch.rand(size=(224,224,3)) #height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [26]:
random_image_size_tensor

tensor([[[0.2894, 0.4057, 0.5233],
         [0.2240, 0.1208, 0.9065],
         [0.1630, 0.6421, 0.0311],
         ...,
         [0.9778, 0.6523, 0.7967],
         [0.3862, 0.9319, 0.3381],
         [0.5947, 0.3056, 0.3231]],

        [[0.1299, 0.8929, 0.6571],
         [0.0710, 0.0647, 0.1503],
         [0.3646, 0.3419, 0.1180],
         ...,
         [0.3454, 0.9819, 0.7901],
         [0.8625, 0.4418, 0.3381],
         [0.3603, 0.6210, 0.4969]],

        [[0.1230, 0.3356, 0.4075],
         [0.7303, 0.3033, 0.3670],
         [0.2812, 0.3822, 0.7012],
         ...,
         [0.1510, 0.3751, 0.5722],
         [0.4894, 0.7107, 0.0071],
         [0.6259, 0.6247, 0.8412]],

        ...,

        [[0.0231, 0.0420, 0.1389],
         [0.1013, 0.6709, 0.2383],
         [0.0120, 0.9181, 0.3070],
         ...,
         [0.3279, 0.6645, 0.8423],
         [0.2049, 0.6743, 0.2401],
         [0.7492, 0.7524, 0.8878]],

        [[0.8786, 0.1998, 0.4504],
         [0.9109, 0.0441, 0.7549],
         [0.

In [27]:
torch.rand(3,3)

tensor([[0.1645, 0.8385, 0.3113],
        [0.4022, 0.8609, 0.4403],
        [0.6183, 0.2677, 0.1737]])

###Zeroes and Ones

In [28]:
zeros =torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
#Create t4ensor of one
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
ones.dtype

torch.float32

##Creating a range of tensors and tensors like

In [32]:
one_to_ten=torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
#use torch range
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

TENSOR DATA TYPES

In [35]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None,
                             device="cuda",
                             requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [36]:
float_32_tensor.dtype

torch.float32

In [37]:
float_16_tensor=torch.tensor([3.0,6.0,9.0],dtype=torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [38]:
float_16_tensor.dtype

torch.float16

In [39]:
float_16_tensor=torch.tensor([3.0,6.0,9.0],dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [40]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [41]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

In [42]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.long,
                           device="cuda")
print(int_32_tensor)
int_32_tensor

tensor([3, 6, 9], device='cuda:0')


tensor([3, 6, 9], device='cuda:0')

In [43]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

In [44]:
!git add .

In [45]:
!git commit -m "tensor update"

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean


In [47]:
!git push -u /content/Pytotch_zero_to_mastery/00_pytorch_fundamentals_video.ipynb

fatal: invalid gitfile format: /content/Pytotch_zero_to_mastery/00_pytorch_fundamentals_video.ipynb
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
