<a href="https://colab.research.google.com/github/raiyan666/Pytorch_zero_to_mastery/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git --version


git version 2.34.1


In [ ]:
!git config --global user.email "raiyan.yead124@gmail.com"
!git config --global user.name "raiyan666"

In [ ]:
!git clone https://github.com/raiyan666/Pytotch_zero_to_mastery.git
%cd Pytotch_zero_to_mastery

Cloning into 'Pytotch_zero_to_mastery'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (6/6), done.
/content/Pytotch_zero_to_mastery


In [ ]:
# !nvidia-smi

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


###Introduction To Tensor
###Creating Tensor  

In [ ]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python int
scalar.item()

7

In [ ]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix=torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[1]

tensor([ 9, 10])

In [ ]:
matrix[0]

tensor([7, 8])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
#Tensor
tensor=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,3,5]]])
tensor


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 3, 5]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 3, 5]])

###Random Tensors

In [ ]:
#Create a random tensor of size(3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.8789, 0.8513, 0.3650, 0.3226],
        [0.2744, 0.7024, 0.1738, 0.3811],
        [0.9775, 0.5055, 0.6149, 0.7436]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_image_size_tensor=torch.rand(size=(224,224,3)) #height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_image_size_tensor

tensor([[[0.2894, 0.4057, 0.5233],
         [0.2240, 0.1208, 0.9065],
         [0.1630, 0.6421, 0.0311],
         ...,
         [0.9778, 0.6523, 0.7967],
         [0.3862, 0.9319, 0.3381],
         [0.5947, 0.3056, 0.3231]],

        [[0.1299, 0.8929, 0.6571],
         [0.0710, 0.0647, 0.1503],
         [0.3646, 0.3419, 0.1180],
         ...,
         [0.3454, 0.9819, 0.7901],
         [0.8625, 0.4418, 0.3381],
         [0.3603, 0.6210, 0.4969]],

        [[0.1230, 0.3356, 0.4075],
         [0.7303, 0.3033, 0.3670],
         [0.2812, 0.3822, 0.7012],
         ...,
         [0.1510, 0.3751, 0.5722],
         [0.4894, 0.7107, 0.0071],
         [0.6259, 0.6247, 0.8412]],

        ...,

        [[0.0231, 0.0420, 0.1389],
         [0.1013, 0.6709, 0.2383],
         [0.0120, 0.9181, 0.3070],
         ...,
         [0.3279, 0.6645, 0.8423],
         [0.2049, 0.6743, 0.2401],
         [0.7492, 0.7524, 0.8878]],

        [[0.8786, 0.1998, 0.4504],
         [0.9109, 0.0441, 0.7549],
         [0.

In [ ]:
torch.rand(3,3)

tensor([[0.1645, 0.8385, 0.3113],
        [0.4022, 0.8609, 0.4403],
        [0.6183, 0.2677, 0.1737]])

###Zeroes and Ones

In [ ]:
zeros =torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Create t4ensor of one
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

##Creating a range of tensors and tensors like

In [ ]:
one_to_ten=torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#use torch range
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

TENSOR DATA TYPES

In [ ]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None,
                             device="cuda",
                             requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor=torch.tensor([3.0,6.0,9.0],dtype=torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor=torch.tensor([3.0,6.0,9.0],dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

In [ ]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.long,
                           device="cuda")
print(int_32_tensor)
int_32_tensor

tensor([3, 6, 9], device='cuda:0')


tensor([3, 6, 9], device='cuda:0')

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

In [ ]:
tensor= torch.tensor([1,2,3])
tensor +10

tensor([11, 12, 13])

In [ ]:
tensor * 10
tensor

tensor([1, 2, 3])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [ ]:
print(tensor ,"*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.88 ms, sys: 0 ns, total: 1.88 ms
Wall time: 2.25 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 63 µs, sys: 12 µs, total: 75 µs
Wall time: 80.3 µs


tensor(14)

In [ ]:
tensor @ tensor
# for natrix multiplication

tensor(14)

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.4686, 0.3198, 0.7429],
        [0.5955, 0.3931, 0.8816],
        [0.0359, 0.0263, 0.0653]])

### most common errors in deep learning: shape errors

In [ ]:
tensor_A=torch.tensor([[1,2],
                      [3,4],
                      [5,6]])
tensor_B=torch.tensor([[7,10],
                      [8,11],
                      [9,12]])
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding min, max etc. (tensor aggregation)

In [ ]:
x=torch.arange(0,100,10)


In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
x.dtype

torch.int64

In [ ]:
 torch.mean(x.type(torch.float32)),  x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

Find positional min max

In [ ]:
x.argmin() # find position of minimum value of argmin

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

In [ ]:
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

Reshaping, stacking, squeezing and unsqueezing tensors

In [3]:
import torch
x=torch.arange(1,11)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [4]:
x_reshaped=x.reshape(1,10)

_reshaped, x_reshaped.shape

NameError: name '_reshaped' is not defined

In [5]:
x_reshaped=x.reshape(2,9)
x_reshaped, x_reshaped.shape

RuntimeError: shape '[2, 9]' is invalid for input of size 10

In [6]:
x_reshaped=x.reshape(5,2)
x_reshaped, x_reshaped.shape


(tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]),
 torch.Size([5, 2]))

In [7]:
x_reshaped=x.reshape(10,1)
x_reshaped, x_reshaped.shape

(tensor([[ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10]]),
 torch.Size([10, 1]))

In [8]:
x=torch.arange(1,10)
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [9]:
x_reshaped=x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [10]:
z=x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

z[:,0]=5
z,x
#changing z changes x

In [18]:
z[:,0]=5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [19]:
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [20]:
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [21]:
x_stacked=torch.stack([x,x,x,x],dim=2)
x_stacked

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [22]:
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [24]:
x_hstacked=torch.hstack([x,x,x,x])
x_hstacked

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9, 5, 2, 3, 4, 5, 6, 7, 8, 9, 5, 2, 3, 4, 5, 6,
        7, 8, 9, 5, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x_hstacked=torch.hstack([x,x,x,x],dim=2)
x_hstacked

TypeError: hstack() got an unexpected keyword argument 'dim'

In [28]:
x_reshaped.shape

torch.Size([1, 9])

In [30]:
x_reshaped

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [29]:
x_reshaped.squeeze()

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed=x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shaped: {x_squeezed.shape}")

Previous tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New shaped: torch.Size([9])


In [35]:
print(f"previous target: {x_squeezed}")
print(f"previous shape: {x_squeezed.shape}")
x_unsqueezed=x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor:{x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

previous target: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
previous shape: torch.Size([9])

New tensor:tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])


In [34]:
print(f"previous target: {x_squeezed}")
print(f"previous shape: {x_squeezed.shape}")
x_unsqueezed=x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor:{x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

previous target: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
previous shape: torch.Size([9])

New tensor:tensor([[5],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
New shape: torch.Size([9, 1])


In [37]:
print(f"previous target: {x_squeezed}")
print(f"previous shape: {x_squeezed.shape}")
x_unsqueezed=x_squeezed.unsqueeze(dim=2)
print(f"\nNew tensor:{x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

previous target: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
previous shape: torch.Size([9])


IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [40]:
x_original=torch.rand(size=(224,224,3))
#permute og tensor to reaarange the axis (or dim )order
x_permuted=x_original.permute(2,0,1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [43]:
x_original[0,0,0]=666666
x_original[0,0,0],x_permuted[0,0,0]

(tensor(666666.), tensor(666666.))

In [46]:
x_original[0,1,0]=666666
x_original[0,1,0],x_permuted[0,0,1]

(tensor(666666.), tensor(666666.))

Indexing

In [47]:
import torch
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [48]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [49]:
x[0][0]

tensor([1, 2, 3])

In [50]:
x[0][0][0]

tensor(1)

In [51]:
x[:,0]

tensor([[1, 2, 3]])

In [53]:
x[:,:,1] #all values of 0 and 1st dimension and 1st indices of 2nd dimension

tensor([[2, 5, 8]])

In [55]:
#all values of 0 dimension but only 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [56]:
#get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [60]:
#index on x to return 9
x[:,2,2]

tensor([9])

In [58]:
#index to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

Pytorch tensor and Numpy


In [61]:
import torch
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [62]:
array.dtype

dtype('float64')

In [63]:
torch.arange(1.0,8.0).dtype

torch.float32

In [64]:
import torch
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array).type(torch.float32)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [65]:
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [66]:
#Tensor to numpy
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [67]:
tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))